name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand what you'd like to see.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What would you like to be able to do?
      placeholder: "I would like to..."
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: "I think it should..."
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
  
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New accessibility example
        - Documentation improvement
        - Beamer migration guide
        - New template option
        - Build/compilation improvement
        - Other
    validations:
      required: true
  
  - type: checkboxes
    id: accessibility
    attributes:
      label: Accessibility Considerations
      description: Does this feature maintain or improve accessibility?
      options:
        - label: This feature maintains WCAG 2.1 Level AA compliance
          required: true
        - label: This feature has been tested with screen readers (if applicable)
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
