name: Question or Help
description: Ask a question about using the template
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Need help with the template? Ask away! Please check the README and existing issues first.
  
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true
  
  - type: dropdown
    id: question-type
    attributes:
      label: Question Category
      options:
        - Installation/Setup
        - Compilation issues
        - Migrating from Beamer
        - Accessibility features
        - Font configuration
        - LuaLaTeX vs pdfLaTeX
        - PDF/A compliance
        - General usage
        - Other
    validations:
      required: true
  
  - type: textarea
    id: what-tried
    attributes:
      label: What Have You Tried?
      description: What have you already tried to solve this?
  
  - type: input
    id: texlive-version
    attributes:
      label: TeX Live Version
      description: Output of `tlmgr --version` (if relevant)
      placeholder: "e.g., TeX Live 2024"
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details that might help us answer your question
